#!/usr/bin/env node
/*
 * Generates the campaign into js/levels.js, in parallel across CPU cores.
 * Deterministic: level n always comes from the same seed, so a rebuild after
 * a tuning change is reproducible.
 *
 *   node tools/build-levels.js [count=200]
 */
const { Worker, isMainThread, parentPort, workerData } = require('worker_threads');
const os = require('os');
const fs = require('fs');
const path = require('path');
const C = require('../js/core.js');

function buildLevel(n) {
  const spec = C.campaignSpec(n);
  const candidates = spec.kind === 'boss' || spec.kind === 'hard' ? 36 : 24;
  const lvl = C.generate(spec, C.hashString('campaign-v3-' + n), { candidates });
  const enc = lvl.tubes.map((t) => t.map((c) => String.fromCharCode(97 + c)).join('')).join(',');
  const id = C.puzzleId(lvl.tubes, lvl.cap);
  return { n, spec, lvl, row: { id, c: lvl.cap, t: enc, p: lvl.par, s: lvl.score, k: spec.kind } };
}

if (!isMainThread) {
  parentPort.on('message', (n) => parentPort.postMessage(buildLevel(n)));
  return;
}

const count = +process.argv[2] || C.TOTAL_LEVELS;
const threads = Math.max(1, Math.min(os.cpus().length - 1, 12));
const t0 = Date.now();
const rows = new Array(count);
// Hardest levels first so the slow ones don't straggle at the end.
const queue = Array.from({ length: count }, (_, i) => i + 1).sort((a, b) => b - a);
let done = 0;

for (let w = 0; w < threads; w++) {
  const worker = new Worker(__filename, { workerData: {} });
  const next = () => (queue.length ? worker.postMessage(queue.shift()) : worker.terminate());
  worker.on('message', ({ n, spec, lvl, row }) => {
    rows[n - 1] = row;
    done++;
    const aim = `target ${spec.target.toFixed(2)}`;
    process.stderr.write(
      `${String(n).padStart(3)}  ${spec.kind.padEnd(8)} ${String(spec.colors).padStart(2)}c/${spec.cap}h  par ${String(lvl.par).padStart(2)}  ` +
      `${aim}  score ${lvl.score.toFixed(2)}  rating ${C.rating(lvl.score)}   [${done}/${count}]\n`,
    );
    if (done === count) finish();
    next();
  });
  next();
}
void workerData;

function finish() {
  const out =
    '// Generated by tools/build-levels.js. Do not edit by hand.\n' +
    '// id: content id (saved progress is keyed by it), c: tube height, t: tubes bottom→top (a = palette 0),\n' +
    '// p: fewest moves, s: difficulty score, k: kind\n' +
    '(function (root) {\n  const LEVELS = [\n    ' + rows.map((r) => JSON.stringify(r)).join(',\n    ') + ',\n  ];\n' +
    "  if (typeof module === 'object' && module.exports) module.exports = LEVELS; else root.SortLevels = LEVELS;\n" +
    "})(typeof self !== 'undefined' ? self : this);\n";
  fs.writeFileSync(path.join(__dirname, '..', 'js', 'levels.js'), out);
  const dupes = rows.length - new Set(rows.map((r) => r.id)).size;
  if (dupes) process.stderr.write(`warning: ${dupes} duplicate puzzle ids\n`);
  process.stderr.write(`wrote ${rows.length} levels in ${((Date.now() - t0) / 1000).toFixed(1)}s on ${threads} threads\n`);
}
